trigger:
- main
- develop
pool:
  name: ubuntu
variables:
  - group: Polaris SAST scan variables
steps:
- task: JavaToolInstaller@0
  displayName: 'Install JDK'
  inputs:
    versionSpec: 21
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    options: '-B -DskipTests'
- task: BlackDuckSecurityScan@2
  displayName: 'Polaris Scan'
  inputs:
    polaris_server_url: $(POLARIS_SERVERURL)
    polaris_access_token: $(POLARIS_ACCESSTOKEN)
    polaris_assessment_types: 'SAST,SCA'
    polaris_application_name: TEST_APP
    polaris_prcomment_enabled: true
    polaris_reports_sarif_create: true
    coverity_build_command: mvn -B -DskipTests package
    coverity_clean_command: mvn -B clean
    azure_token: $(System.AccessToken)
    include_diagnostics: false
    mark_build_status: 'SucceededWithIssues'
